<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <DebugType>portable</DebugType>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <RootNamespace>EmbedCSharpLoader.Bootstrap</RootNamespace>
    </PropertyGroup>

</Project>
