<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <AssemblyVersion>0.0.6.0</AssemblyVersion>
        <DebugType>portable</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SharpDX" Version="4.2.0" />
        <PackageReference Include="SharpDX.XInput" Version="4.2.0" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="UnrealEngine.Runtime">
            <HintPath>..\GameDll\UnrealEngine.Runtime.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HarmonyPrepatcher\src\Harmony\Lib.Harmony\Lib.Harmony.csproj" />
      <ProjectReference Include="..\ReadyM.Loader.Wukong.Bootstrap\ReadyM.Loader.Wukong.Bootstrap.csproj" />
    </ItemGroup>

</Project>
