<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <AssemblyVersion>0.0.6.0</AssemblyVersion>
        <DebugType>portable</DebugType>
        <TargetExt>.bin</TargetExt>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CSharpModBase\CSharpModBase.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Mono.Cecil" Version="0.11.5" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="UnrealEngine">
            <HintPath>..\GameDll\UnrealEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnrealEngine.Runtime">
            <HintPath>..\GameDll\UnrealEngine.Runtime.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
